baseURL = 'https://federico.cfinet.org/'
locale = 'en-us'
title = 'My New Hugo Project'
theme = 'hello-friend-ng'

[pagination]
pagerSize = 10

[params]
homeSubtitle = 'A simple and beautiful blog'
homeIntro = 'Ciao, sono Federico. Questo è il mio spazio personale online: un luogo dove condivido idee, progetti e cose che mi incuriosiscono.'
dateform = 'Jan 2, 2006'
dateformShort = 'Jan 2'
dateformNum = '2006-01-02'
dateformNumTime = '2006-01-02 15:04'
enableThemeToggle = true

[params.logo]
logoMark = '>'
logoText = 'fcinet'
logoHomeLink = '/'

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'

[[menu.main]]
identifier = 'about'
name = 'About me'
url = '/about/'
