baseURL = 'https://federico.cfinet.org/'
locale = 'en-us'
title = 'Federico's notebook'
theme = 'hello-friend-ng'

[pagination]
pagerSize = 10

[params]
homeSubtitle = 'My blog About Networks, Linux, mobile networks...and many more'
dateform = 'Jan 2, 2006'
dateformShort = 'Jan 2'
dateformNum = '2006-01-02'
dateformNumTime = '2006-01-02 15:04'
enableThemeToggle = true

[params.logo]
logoMark = '>'
logoText = 'fcinet'
logoHomeLink = '/'

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'

[[menu.main]]
identifier = 'about'
name = 'About me'
url = '/about/'
